import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { cn } from "../lib/utils"
import { ClerkProvider } from "@clerk/nextjs"
import SyncMe from "../components/SyncMe";
import ReminderToaster from "../components/ReminderToaster";
import ReminderPuller from "../components/ReminderPuller";



const inter = Inter({ subsets: ["latin"], variable: "--font-sans" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en">
        <body
          className={cn(
            "min-h-screen, bg-background font-sans antialiased",
            inter.variable
          )}
        >
          <SyncMe />
           <ReminderPuller />
          {children}
        </body>
      </html>
      </ClerkProvider>
   
  )
}